"""Условная маршрутизация и шлюз — сторона основного бота. Части пакета:

  slots    шлюзовое устройство и слоты: карточка устройства, имя и состояние слота, строки списка, экран «🛰 Шлюзы»
  card     карточка слота: сервисы, свои списки, канал, трафик
  dialogs  диалоги слота: локальная сеть, роутер, переключение, VPN-транзит, подпись, снятие
  assign   назначение шлюза: выбор устройства, новое устройство, токен, итог развёртывания
  access   параметры и доступ: настройки, статусные строки, файл конфигурации и установка, личный список доменов, уведомления
"""

from .slots import (vps_hostname, ping_line, ext_ip_line, ping_fmt, _slot_dot, gateway_role_line, gateway_device_card, gateway_claim_marked, gateway_claim_already, _slot_down_for, _bot_link, _slot_note, ROUTER_IP_PLACEHOLDER, ROUTING_NAME, slot_name, slot_status, slot_ref, _slot_ping_tail, slot_line, peer_nets_line, GATEWAYS_ABOUT, ROUTING_PROVISION_INTRO, SETTINGS_ROUTING_ABSENT, GATEWAYS_OFF, SETTINGS_ROUTING_SUBOFF, GATEWAYS_AUTO_OFF, _lists_tail, gateways_text, agent_bot_line)  # noqa: F401
from .card import (services_line, own_lists_line, channel_lines, _gw_traffic, gateway_card_text, gateway_edit_text)  # noqa: F401
from .dialogs import (_reissue_or_channel, already_state, GW_TOKEN_NOT_FORGOTTEN, gateway_lan_ask, GATEWAY_LAN_NO_SUBNET, ROUTER_TABS, gateway_router_text, gateway_switch_ask, gateway_peer_ask, gateway_home_text, gateway_home_report, gateway_label_text, gateway_remove_ask, gateway_removed)  # noqa: F401
from .assign import (GATEWAY_CHOOSE_INTRO, GATEWAY_STANDBY_CHOOSE_INTRO, GATEWAY_PICK_INTRO, GATEWAY_PICK_EMPTY, gateway_replace_intro, gateway_mark_ask, gateway_new_ask, gateway_ask_token, routing_provisioned)  # noqa: F401
from .access import (routing_params_text, routing_users_text, ROUTING_DISABLE_CONFIRM, gateway_bundle_applied_text, gateway_installed_text, gateway_bundle_caption, gateway_plain_bundle_caption, routing_provision_failed, gateway_install_instructions, routing_status_line, GW_CARD_PAYLOAD, routing_admin_status_line, ROUTING_ABOUT, ROUTING_ADD_PROMPT, ROUTING_APPLY_HINT, ROUTING_SITES_ABOUT, _short, routing_domain_removed, _lent_out_lines, routing_panel_text, routing_sites_text, routing_add_report, routing_clear_ask, ROUTING_UNAVAILABLE, ROUTING_NOT_ALLOWED_ADMIN, routing_gateway_warning, ROUTING_GRANTED_NOTICE, routing_granted_holder_notice, routing_revoked_holder_notice, ROUTING_REVOKED_NOTICE)  # noqa: F401

__all__ = ["vps_hostname", "ping_line", "ext_ip_line", "ping_fmt", "_slot_dot", "gateway_role_line", "gateway_device_card", "gateway_claim_marked", "gateway_claim_already", "_slot_down_for", "_bot_link", "_slot_note", "ROUTER_IP_PLACEHOLDER", "ROUTING_NAME", "slot_name", "slot_status", "slot_ref", "_slot_ping_tail", "slot_line", "peer_nets_line", "GATEWAYS_ABOUT", "ROUTING_PROVISION_INTRO", "SETTINGS_ROUTING_ABSENT", "GATEWAYS_OFF", "SETTINGS_ROUTING_SUBOFF", "GATEWAYS_AUTO_OFF", "_lists_tail", "gateways_text", "agent_bot_line", "services_line", "own_lists_line", "channel_lines", "_gw_traffic", "gateway_card_text", "gateway_edit_text", "_reissue_or_channel", "already_state", "GW_TOKEN_NOT_FORGOTTEN", "gateway_lan_ask", "GATEWAY_LAN_NO_SUBNET", "ROUTER_TABS", "gateway_router_text", "gateway_switch_ask", "gateway_peer_ask", "gateway_home_text", "gateway_home_report", "gateway_label_text", "gateway_remove_ask", "gateway_removed", "GATEWAY_CHOOSE_INTRO", "GATEWAY_STANDBY_CHOOSE_INTRO", "GATEWAY_PICK_INTRO", "GATEWAY_PICK_EMPTY", "gateway_replace_intro", "gateway_mark_ask", "gateway_new_ask", "gateway_ask_token", "routing_provisioned", "routing_params_text", "routing_users_text", "ROUTING_DISABLE_CONFIRM", "gateway_bundle_applied_text", "gateway_installed_text", "gateway_bundle_caption", "gateway_plain_bundle_caption", "routing_provision_failed", "gateway_install_instructions", "routing_status_line", "GW_CARD_PAYLOAD", "routing_admin_status_line", "ROUTING_ABOUT", "ROUTING_ADD_PROMPT", "ROUTING_APPLY_HINT", "ROUTING_SITES_ABOUT", "_short", "routing_domain_removed", "_lent_out_lines", "routing_panel_text", "routing_sites_text", "routing_add_report", "routing_clear_ask", "ROUTING_UNAVAILABLE", "ROUTING_NOT_ALLOWED_ADMIN", "routing_gateway_warning", "ROUTING_GRANTED_NOTICE", "routing_granted_holder_notice", "routing_revoked_holder_notice", "ROUTING_REVOKED_NOTICE"]
